<a href="https://colab.research.google.com/github/Lubna-AlAmri/Machine-Learning-/blob/main/Bayesian_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Naive Bayes Example

The ususal imports, as well as some additional ones for computing NB later on

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB

Get the data

In [ ]:
url = 'https://raw.githubusercontent.com/sjwhitworth/golearn/master/examples/datasets/tennis.csv'

df = pd.read_csv(url)

Have a look at the data in the datafare

```python
df
```


In [ ]:
df

outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [ ]:
print("Current DataFrame (df):")
display(df)
print(f"Number of rows in df: {len(df)}")

Current DataFrame (df):


outlook  temp humidity  windy   play
0      sunny   hot     high  False  False
1      sunny   hot     high   True  False
2   overcast   hot     high  False   True
3      rainy  mild     high  False   True
4      rainy  cool   normal  False   True
5      rainy  cool   normal   True  False
6   overcast  cool   normal   True   True
7      sunny  mild     high  False  False
8      sunny  cool   normal  False   True
9      rainy  mild   normal  False   True
10     sunny  mild   normal   True   True
11  overcast  mild     high   True   True
12  overcast   hot   normal  False   True
13     rainy  mild     high   True  False

Number of rows in df: 14


Using ```describe()``` one can see a summary of the individual columns.

```python
df.describe()
```

In [ ]:
df.describe()

outlook  temp humidity  windy play
count       14    14       14     14   14
unique       3     3        2      2    2
top      sunny  mild     high  False  yes
freq         5     6        7      8    9

Using ```dtypes``` one can see a summary of the individual columns.

```python
df.dtypes
```

In [ ]:
df.dtypes

outlook     object
temp        object
humidity    object
windy         bool
play        object
dtype: object

To change the values (and to some extend the type) of a column within a dataframe one can map values to other values using the ```map(<dictionary>)``` method.

Reassigining a dataframe column to the same column replaces all values.

```python

df['play'] = df['play'].map({'yes':True,'no':False})

```
Will replace all ```'yes'``` to ```True``` and ```'no'``` to ```False```

In [ ]:
df['play'] = df['play'].map({'yes':True,'no':False})

Have a look at the types again and at the complete dataframe

In [ ]:
df

outlook  temp humidity  windy   play
0      sunny   hot     high  False  False
1      sunny   hot     high   True  False
2   overcast   hot     high  False   True
3      rainy  mild     high  False   True
4      rainy  cool   normal  False   True
5      rainy  cool   normal   True  False
6   overcast  cool   normal   True   True
7      sunny  mild     high  False  False
8      sunny  cool   normal  False   True
9      rainy  mild   normal  False   True
10     sunny  mild   normal   True   True
11  overcast  mild     high   True   True
12  overcast   hot   normal  False   True
13     rainy  mild     high   True  False

In [ ]:
df. dtypes


outlook     object
temp        object
humidity    object
windy         bool
play          bool
dtype: object

## Using Naive Bayes of sklearn

### Encoding

Before using the python library for Naive Bayes, we have to first encode the values into numbers, as sklearn cannot deal with string values

For this, we will use a so-called ```LabelEncoder```

In [ ]:
#creating labelEncoder
le = preprocessing.LabelEncoder()

To translate all string values into numbers, we can use the following commaand:

```python
le.fit_transform(df['outlook'])
```

Try it out.

In [ ]:
le.fit_transform(df['outlook'])

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

We want to leave the original dataframe as it is, so we copy it and put it into a new variable

In [ ]:
df_new = df.copy()

Now, replace ```'outlook'```, ```'temp'```, and ```'humidity'``` with transformed columns in df_new.



In [ ]:
le.fit_transform(df_new['humidity'])

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [ ]:
le.fit_transform(df_new['temp'])

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

### Naive Bayes (GaussianNB)

Let's create a Naive Bayes model using GaussianNB. Once the model is created, one can fit it using the existing data. Once the model is fitted, it can be used to predict the outcome as well as the correcponding probabilities:



```python
#Create a Gaussian Classifier
model = GaussianNB()

# fit the model
model.fit(df_new[['outlook']],df_new['play'])

# predict
model.predict([[0]])
model.predict_proba([[0]])

```

Try it out, predict for a number of values and extend it for more variables (columns).


In [ ]:

# Create a Gaussian Classifier
model = GaussianNB()

# Before fitting the model, encode the categorical features into numerical values.
# This step was missed, causing the ValueError.
# Apply LabelEncoder to 'outlook', 'temp', and 'humidity' columns in df_new.

# Assuming le (LabelEncoder) has already been initialized in a previous cell.
# If not, it needs to be initialized here: le = preprocessing.LabelEncoder()

df_new['outlook'] = le.fit_transform(df_new['outlook'])
df_new['temp'] = le.fit_transform(df_new['temp'])
df_new['humidity'] = le.fit_transform(df_new['humidity'])

# fit the model
model.fit(df_new[['outlook']],df_new['play'])


# predict
model.predict([[1]])
model.predict_proba([[1]])


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([[0.30460979, 0.69539021]])

In [ ]:
# This prints the order of the classes (e.g., [False, True]) that the model learned, which dictates how to interpret predict_proba results.
print(model.classes_)

[False  True]


In [ ]:
priors_array

NameError: name 'priors_array' is not defined

In [ ]:
# To inject prior knowlege into a model, we use the prior function for all classes/features.

# Task
Please provide two prior probabilities for the 'play' variable, corresponding to 'False' and 'True' respectively. These should be a list of two floats that sum to 1. For example, `[0.3, 0.7]` if you want 30% prior probability for 'False' and 70% for 'True'.

## Understand current model and classes

### Subtask:
Review the current Gaussian Naive Bayes model configuration and identify the order of classes for the 'play' variable (True/False) to correctly set the priors.


## Prompt for new priors

### Subtask:
Ask the user to provide the desired prior probabilities for the 'False' and 'True' classes of the 'play' variable. The input should be a list or array of two floats that sum to 1.


**Reasoning**:
To prompt the user for prior probabilities, I will create a code block that uses the `input()` function to ask for a list of two floats and then evaluate the input as a Python expression, storing it in a variable.



In [ ]:
print("### Subtask\nAsk the user to provide the desired prior probabilities for the 'False' and 'True' classes of the 'play' variable. The input should be a list or array of two floats that sum to 1.\n")
priors_input_str = input("#### Instructions\nPlease provide two prior probabilities for the 'play' variable, corresponding to 'False' and 'True' respectively. These should be a list of two floats that sum to 1. For example, [0.3, 0.7] if you want 30% prior probability for 'False' and 70% for 'True'. Enter your priors as a Python list of floats: ")

try:
    priors_array = eval(priors_input_str)
    if not isinstance(priors_array, list) or len(priors_array) != 2 or not all(isinstance(x, (int, float)) for x in priors_array):
        raise ValueError("Input must be a list of two numbers.")
    if not np.isclose(sum(priors_array), 1.0):
        raise ValueError("The sum of probabilities must be close to 1.0.")
    print(f"Received prior probabilities: {priors_array}")
except (SyntaxError, NameError, ValueError) as e:
    print(f"Invalid input. Please provide a valid list of two floats that sum to 1. Error: {e}")
    priors_array = None # Reset to None if invalid


### Subtask
Ask the user to provide the desired prior probabilities for the 'False' and 'True' classes of the 'play' variable. The input should be a list or array of two floats that sum to 1.



KeyboardInterrupt: Interrupted by user

# Task
Apply `sklearn.preprocessing.OrdinalEncoder` to the 'outlook', 'temp', and 'humidity' columns in a copy of the original DataFrame `df` (named `df_new`), confirming the successful encoding of these categorical columns into numerical types without using an explicit loop, and explain the benefits of using `OrdinalEncoder` for this purpose.

## Identify Categorical Columns

### Subtask:
Identify the columns in `df_new` that are currently `object` type (strings) and need to be numerically encoded. These are 'outlook', 'temp', and 'humidity'.


The columns that need to be numerically encoded are 'outlook', 'temp', and 'humidity'.

**Reasoning**:
To fulfill the instructions to list the categorical columns and store them in a Python list for later use, I will create a code block that defines this list.



In [ ]:
categorical_cols = ['outlook', 'temp', 'humidity']
print(f"Categorical columns identified for encoding: {categorical_cols}")

Categorical columns identified for encoding: ['outlook', 'temp', 'humidity']


**Reasoning**:
To encode the identified categorical columns ('outlook', 'temp', 'humidity') in `df_new` into numerical types, I will use `sklearn.preprocessing.OrdinalEncoder`. This will be applied to the relevant columns, and then I will display the head of the modified DataFrame and its data types to confirm the transformation.



In [ ]:
from sklearn.preprocessing import OrdinalEncoder

# Initialize OrdinalEncoder
oencoder = OrdinalEncoder()

# Apply OrdinalEncoder to the identified categorical columns in df_new
df_new[categorical_cols] = oencoder.fit_transform(df_new[categorical_cols])

print("DataFrame after Ordinal Encoding:")
display(df_new.head())
print("\nData types after Ordinal Encoding:")
display(df_new.dtypes)

DataFrame after Ordinal Encoding:


outlook  temp  humidity  windy   play
0      2.0   1.0       0.0  False  False
1      2.0   1.0       0.0   True  False
2      0.0   1.0       0.0  False   True
3      1.0   2.0       0.0  False   True
4      1.0   0.0       1.0  False   True


Data types after Ordinal Encoding:


outlook     float64
temp        float64
humidity    float64
windy          bool
play           bool
dtype: object

### Benefits of using OrdinalEncoder

`OrdinalEncoder` is a suitable choice for encoding categorical features like 'outlook', 'temp', and 'humidity' when there's an inherent order or ranking among the categories, or when the number of unique categories is relatively small and one-hot encoding would create too many new columns.

Benefits include:

1.  **Efficiency**: It transforms multiple categorical columns at once, making the code concise and efficient compared to manual mapping or using `LabelEncoder` in a loop.
2.  **Handling New Categories**: When used with `handle_unknown='use_encoded_value'` and `unknown_value=-1` (or similar), it can gracefully handle new, unseen categories during prediction without raising errors, although in this specific example, all categories are known.
3.  **Numerical Representation**: Converts string categories into numerical integers, which is a prerequisite for many machine learning algorithms like Naive Bayes, which operate on numerical data.
4.  **No Dummy Variable Trap (for some models)**: Unlike `OneHotEncoder`, it doesn't create new columns for each category, avoiding potential issues like the dummy variable trap if not handled correctly, and keeping the feature space smaller.

## Final Task

### Subtask:
Confirm that the categorical columns have been successfully encoded without using an explicit loop, and explain the benefits of using `OrdinalEncoder` for this purpose.


## Summary:

### Q&A
1.  **Have the categorical columns been successfully encoded without using an explicit loop?**
    Yes, the categorical columns 'outlook', 'temp', and 'humidity' were successfully encoded into numerical types without using an explicit loop by applying `OrdinalEncoder` directly to the selected columns.
2.  **What are the benefits of using `OrdinalEncoder` for this purpose?**
    `OrdinalEncoder` offers several benefits:
    *   **Efficiency**: It transforms multiple categorical columns simultaneously, making the process concise.
    *   **Numerical Representation**: It converts string categories into numerical integers, which is a prerequisite for many machine learning algorithms.
    *   **Handling New Categories**: When configured, it can gracefully handle unseen categories during prediction.
    *   **Space Efficiency**: Unlike one-hot encoding, it does not create new columns for each category, maintaining a smaller feature space and potentially avoiding the dummy variable trap in certain contexts.

### Data Analysis Key Findings
*   The categorical columns 'outlook', 'temp', and 'humidity' were successfully identified for encoding.
*   After applying `OrdinalEncoder`, these columns were transformed from `object` (string) type to `float64`, indicating successful numerical encoding.
*   The `df_new.head()` output confirmed that the 'outlook', 'temp', and 'humidity' columns now contain numerical values (e.g., 2.0, 1.0, 0.0) instead of their original string categories.

### Insights or Next Steps
*   `OrdinalEncoder` is an effective and efficient tool for converting multiple categorical features into a numerical format, preparing data for machine learning models that require numerical inputs.
